### ISSUE TITLE
Cloud templates failing to start with latest images

### ISSUE THREAD

**Issue by WhiteMemory99** [ai-dock/stable-diffusion-webui#12]
1. Select any appropriate GPU on Runpod/Vast.ai.
2. Select the template from Readme, leave the default args.
3. Wait for provisioning to finish.

```
Cloning assets into /opt/stable-diffusion-webui/repositories/stable-diffusion-webui-assets...
fatal: could not create work tree dir '/opt/stable-diffusion-webui/repositories/stable-diffusion-webui-assets': Permission denied
Traceback (most recent call last):
  File "/opt/stable-diffusion-webui/launch.py", line 48, in
    main()
  File "/opt/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/opt/stable-diffusion-webui/modules/launch_utils.py", line 410, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "/opt/stable-diffusion-webui/modules/launch_utils.py", line 191, in git_clone
    run(f'"{git}" clone --config core.filemode=false "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}", live=True)
  File "/opt/stable-diffusion-webui/modules/launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone assets.
Command: "git" clone --config core.filemode=false "https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git" "/opt/stable-diffusion-webui/repositories/stable-diffusion-webui-assets"
Error code: 128
```

**Comment by robballantyne** [comment]
New image is building now to resolve the issue.

Sorry for the inconvenience.

**Comment by WhiteMemory99** [comment]
New image works fine, thank you!
